// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SportsbookAggregation.Data;

namespace SportsbookAggregation.Migrations
{
    [DbContext(typeof(Context))]
    [Migration("20200930000000_AddIsAvailableColumn")]
    partial class AddIsAvailableColumn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SportsbookAggregation.Alerts.Models.Alert", b =>
                {
                    b.Property<Guid>("AlertId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<int?>("CurrentAwayMoneyLine")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentAwaySpread")
                        .HasColumnType("double");

                    b.Property<int?>("CurrentAwaySpreadPayout")
                        .HasColumnType("int");

                    b.Property<int?>("CurrentHomeMoneyLine")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentHomeSpread")
                        .HasColumnType("double");

                    b.Property<int?>("CurrentHomeSpreadPayout")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentOver")
                        .HasColumnType("double");

                    b.Property<int?>("CurrentOverPayout")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentUnder")
                        .HasColumnType("double");

                    b.Property<int?>("CurrentUnderPayout")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("binary(16)");

                    b.Property<string>("Type")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("AlertId");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.GamblingSite", b =>
                {
                    b.Property<Guid>("GamblingSiteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("GamblingSiteId");

                    b.ToTable("GamblingSite");

                    b.HasData(
                        new
                        {
                            GamblingSiteId = new Guid("1fcec6f7-84b3-4033-af0f-e1f2bcb8528c"),
                            Name = "Fanduel"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("585e8b23-82e7-468e-b0f3-601cd6eb7a21"),
                            Name = "FoxBet"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("ef4a3b1e-dd09-4e32-a648-097ebae237d1"),
                            Name = "DraftKings"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("a13abd89-8246-4ce9-a3e1-34eee3084748"),
                            Name = "BetRivers"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("3208224c-cbee-408f-b7d8-3ad76f70eaa9"),
                            Name = "Unibet"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("ae98bc03-bf79-491a-8d5a-23acc23908a9"),
                            Name = "Parx"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("89f19651-c30c-4846-8197-8f10e43b4ae6"),
                            Name = "BetAmerica"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("ee7f8f4c-23a7-4c35-a450-fed7cc90a6dd"),
                            Name = "Caesars"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("730346f5-e563-47bf-9230-148d25c424e9"),
                            Name = "SugarHouse"
                        },
                        new
                        {
                            GamblingSiteId = new Guid("eda5febb-1381-411a-88e8-5db158589212"),
                            Name = "Barstool"
                        });
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.Game", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<Guid?>("AwayTeamId")
                        .HasColumnType("binary(16)");

                    b.Property<Guid?>("HomeTeamId")
                        .HasColumnType("binary(16)");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("datetime(6)");

                    b.HasKey("GameId");

                    b.ToTable("Game");
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.GameLine", b =>
                {
                    b.Property<Guid>("GameLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<int?>("AwayMoneyLinePayout")
                        .HasColumnType("int");

                    b.Property<int?>("AwaySpreadPayout")
                        .HasColumnType("int");

                    b.Property<double?>("CurrentOverUnder")
                        .HasColumnType("double");

                    b.Property<double?>("CurrentSpread")
                        .HasColumnType("double");

                    b.Property<Guid>("GamblingSiteId")
                        .HasColumnType("binary(16)");

                    b.Property<Guid>("GameId")
                        .HasColumnType("binary(16)");

                    b.Property<int?>("HomeMoneyLinePayout")
                        .HasColumnType("int");

                    b.Property<int?>("HomeSpreadPayout")
                        .HasColumnType("int");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastRefresh")
                        .HasColumnType("datetime(6)");

                    b.Property<double?>("OpeningOverUnder")
                        .HasColumnType("double");

                    b.Property<double?>("OpeningSpread")
                        .HasColumnType("double");

                    b.Property<int?>("OverPayOut")
                        .HasColumnType("int");

                    b.Property<int?>("UnderPayout")
                        .HasColumnType("int");

                    b.HasKey("GameLineId");

                    b.HasIndex("GamblingSiteId");

                    b.HasIndex("GameId");

                    b.ToTable("GameLine");
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.GameResult", b =>
                {
                    b.Property<Guid>("GameResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<int>("AwayTeamScore")
                        .HasColumnType("int");

                    b.Property<Guid>("GameId")
                        .HasColumnType("binary(16)");

                    b.Property<int>("HomeTeamScore")
                        .HasColumnType("int");

                    b.HasKey("GameResultId");

                    b.HasIndex("GameId");

                    b.ToTable("GameResult");
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.Sport", b =>
                {
                    b.Property<Guid>("SportId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Name")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("SportId");

                    b.ToTable("Sport");

                    b.HasData(
                        new
                        {
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8"),
                            Name = "MLB"
                        },
                        new
                        {
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024"),
                            Name = "NBA"
                        },
                        new
                        {
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be"),
                            Name = "NFL"
                        });
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.Team", b =>
                {
                    b.Property<Guid>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("binary(16)");

                    b.Property<string>("Location")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Mascot")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("SportId")
                        .HasColumnType("binary(16)");

                    b.HasKey("TeamId");

                    b.HasIndex("SportId");

                    b.ToTable("Team");

                    b.HasData(
                        new
                        {
                            TeamId = new Guid("327fa1ce-ebd2-42b5-8ae3-af4e1f85c31b"),
                            Location = "Atlanta",
                            Mascot = "Hawks",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("f4646032-8ce2-4115-aa17-6a3f829c48c6"),
                            Location = "Boston",
                            Mascot = "Celtics",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("51058c98-007a-4a03-a4dc-1678f39d0fe6"),
                            Location = "Brooklyn",
                            Mascot = "Nets",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("dba20e75-2763-45e0-8357-f7abdef5796e"),
                            Location = "Charlotte",
                            Mascot = "Hornets",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("9535fd86-0476-4267-964d-86b6ee59c5f1"),
                            Location = "Chicago",
                            Mascot = "Bulls",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("567d7281-3835-4ebe-9bbc-db22003ef4aa"),
                            Location = "Cleveland",
                            Mascot = "Cavaliers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("f3449c73-2bdf-45d6-a12a-5fcdcdba9c7a"),
                            Location = "Dallas",
                            Mascot = "Mavericks",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("cc3a3123-ffcc-4575-aaf6-908bf0a29ae2"),
                            Location = "Denver",
                            Mascot = "Nuggets",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("136ffb0e-e6db-447f-ac0b-d24d0972c63a"),
                            Location = "Detroit",
                            Mascot = "Pistons",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("a7d2b876-5c8f-40c0-a245-64009f1d6875"),
                            Location = "Golden State",
                            Mascot = "Warriors",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("9cb62c80-9eed-4778-9db9-c96a3f210548"),
                            Location = "Houston",
                            Mascot = "Rockets",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("e07441a3-7862-4aa9-b102-fa9eff3a3d32"),
                            Location = "Indiana",
                            Mascot = "Pacers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("a8427679-a566-4cb6-baf5-90f848a70ef1"),
                            Location = "Los Angeles",
                            Mascot = "Clippers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("d96a3350-0ee1-4ebb-a3c5-7e8d9ffbdbcf"),
                            Location = "Los Angeles",
                            Mascot = "Lakers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("0dcdcb0d-5a8f-4f06-ae40-e6c8f9405a2b"),
                            Location = "Memphis",
                            Mascot = "Grizzlies",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("553993e6-d5d2-41d1-9aa4-96282469b7f4"),
                            Location = "Miami",
                            Mascot = "Heat",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("faae94d4-821c-4089-abc9-00e59164cfe4"),
                            Location = "Milwaukee",
                            Mascot = "Bucks",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("49b08feb-f42e-4003-afea-14e5f967bf83"),
                            Location = "Minnesota",
                            Mascot = "Timberwolves",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("980e2d86-24f5-4db1-9e86-a24f69f64363"),
                            Location = "New Orleans",
                            Mascot = "Pelicans",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("aa91f18e-db7f-49b6-ae39-830232228741"),
                            Location = "New York",
                            Mascot = "Knicks",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("17c82efe-820f-47f1-beda-7ca67f77fffa"),
                            Location = "Oklahoma City",
                            Mascot = "Thunder",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("377a4678-f768-41f8-850e-437b87315b10"),
                            Location = "Orlando",
                            Mascot = "Magic",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("e3708fae-5fc1-40d6-b0bc-10330212eb46"),
                            Location = "Philadelphia",
                            Mascot = "76ers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("9490d52f-d1d1-4ac7-87d0-0ef922f4e3e2"),
                            Location = "Phoenix",
                            Mascot = "Suns",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("a0ada57d-419d-4fec-9d72-a6d6b96fcb34"),
                            Location = "Portland",
                            Mascot = "Trail Blazers",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("adb45183-40f4-4cba-adec-062976372d31"),
                            Location = "Sacramento",
                            Mascot = "Kings",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("2578493d-1735-4427-a2e1-492f8c43fdfd"),
                            Location = "San Antonio",
                            Mascot = "Spurs",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("4d89def6-375b-4b58-8385-858ea8957576"),
                            Location = "Toronto",
                            Mascot = "Raptors",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("104981bd-8e56-4d67-bbd0-f6f1bfd50a2d"),
                            Location = "Utah",
                            Mascot = "Jazz",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("261454ae-5f16-4707-ada1-bff5095f056b"),
                            Location = "Washington",
                            Mascot = "Wizards",
                            SportId = new Guid("2cbbd293-8627-447d-8b20-2c5a4fdaa024")
                        },
                        new
                        {
                            TeamId = new Guid("03f86ef9-e837-4d16-a869-1561dde61798"),
                            Location = "Arizona",
                            Mascot = "Cardinals",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("586fe718-6743-409a-969d-d19bd36d4254"),
                            Location = "Atlanta",
                            Mascot = "Falcons",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("3b88d60b-96a7-411b-a061-d4a581d7a5a6"),
                            Location = "Baltimore",
                            Mascot = "Ravens",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("b62aa542-7d3b-4a85-a4e8-8b6a2d8ebefa"),
                            Location = "Buffalo",
                            Mascot = "Bills",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("48259823-78c5-4c42-ace2-7d59fd6d5b67"),
                            Location = "Carolina",
                            Mascot = "Panthers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("0df55a06-1ce5-41f5-baa8-dedfc9982b14"),
                            Location = "Chicago",
                            Mascot = "Bears",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("3bfcc8bb-b87d-4a1a-adf1-bf1ed1c554f5"),
                            Location = "Cincinnati",
                            Mascot = "Bengals",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("450aa644-fcca-4e1e-9ed2-2eb8e87c6571"),
                            Location = "Cleveland",
                            Mascot = "Browns",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("e5e561ba-70c8-4b72-bd63-d14f9e2db12c"),
                            Location = "Dallas",
                            Mascot = "Cowboys",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("0b093a77-6b07-4207-b27c-848938ce522a"),
                            Location = "Denver",
                            Mascot = "Broncos",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("23390e8c-e70c-48aa-9fab-6a3770d91de4"),
                            Location = "Detroit",
                            Mascot = "Lions",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("7193bfbf-1aa8-480e-88e9-339312ea9da8"),
                            Location = "Green Bay",
                            Mascot = "Packers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("2f8cd4fe-dc9c-4ed1-84d7-1d0923e73ac3"),
                            Location = "Houston",
                            Mascot = "Texans",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("41f2f8a9-4671-41f1-86e5-c388423b5b04"),
                            Location = "Indianapolis",
                            Mascot = "Colts",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("6746d02f-0910-402b-86fc-e5a9a52d2e21"),
                            Location = "Jacksonville",
                            Mascot = "Jaguars",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("d728eb6a-8a28-4c21-a50e-a226b2d5b70f"),
                            Location = "Kansas City",
                            Mascot = "Chiefs",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("952efc18-905f-4ab9-8ac3-4f79b0e068e6"),
                            Location = "Los Angeles",
                            Mascot = "Chargers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("1cf88a9e-82cf-4506-8d3b-ac0b8e8915fd"),
                            Location = "Los Angeles",
                            Mascot = "Rams",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("ec9d7c36-7379-4d1d-8a22-156d4ee83b2a"),
                            Location = "Las Vegas",
                            Mascot = "Raiders",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("1c349295-7317-4ad8-ab5a-13275e3e03c6"),
                            Location = "Miami",
                            Mascot = "Dolphins",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("69d2e5de-9793-4faa-a2a8-9bcc54e656d3"),
                            Location = "Minnesota",
                            Mascot = "Vikings",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("0da464e1-f39c-4049-b312-f2968aa71ae4"),
                            Location = "New England",
                            Mascot = "Patriots",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("71245471-b0ff-4381-bf35-343f698ff077"),
                            Location = "New Orleans",
                            Mascot = "Saints",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("fd59c829-5712-450a-ac75-595757010acc"),
                            Location = "New York",
                            Mascot = "Giants",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("d3cadd00-d44a-4840-9632-5f24d72ef9d3"),
                            Location = "New York",
                            Mascot = "Jets",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("fb02cf5b-4ad9-4131-86ab-9a7f49aaad55"),
                            Location = "Philadelphia",
                            Mascot = "Eagles",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("a3629bd0-3c5b-4de6-a3e4-514333fc3fa5"),
                            Location = "Pittsburgh",
                            Mascot = "Steelers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("dd82688b-9c9d-42ac-975c-d4db4a211d29"),
                            Location = "Seattle",
                            Mascot = "Seahawks",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("8a7cdedd-a273-4320-b479-2eeae69694d2"),
                            Location = "San Francisco",
                            Mascot = "49ers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("360fd180-6f0e-4545-8d14-5f690944cfdc"),
                            Location = "Tampa Bay",
                            Mascot = "Buccaneers",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("4c713570-bf81-4b2f-b170-3258ca86d07e"),
                            Location = "Tennessee",
                            Mascot = "Titans",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("2bf36e69-9abd-40e5-92e3-3817e6c13253"),
                            Location = "Washington",
                            Mascot = "Football Team",
                            SportId = new Guid("6e972a45-6bd9-4085-9a78-faddf46294be")
                        },
                        new
                        {
                            TeamId = new Guid("b80ba92d-3fea-4da0-a47f-f65cd46eb067"),
                            Location = "Arizona",
                            Mascot = "Diamondbacks",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("c6bc8fc8-6391-4af8-9032-364c86ca59d5"),
                            Location = "Atlanta",
                            Mascot = "Braves",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("764f8f26-b02b-43b5-946a-4429ff9d2ae9"),
                            Location = "Baltimore",
                            Mascot = "Orioles",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("7d297cb2-173e-4e4d-9eeb-86aecf711f7b"),
                            Location = "Boston",
                            Mascot = "Red Sox",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("1f0c79e0-65ff-4d92-8b95-7e09f875beac"),
                            Location = "Chicago",
                            Mascot = "Cubs",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("66dfad29-3097-47a0-964b-136fce7fa365"),
                            Location = "Chicago",
                            Mascot = "White Sox",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("bfb3beb9-76aa-4000-b8d5-e7c616d45c8b"),
                            Location = "Cincinnati",
                            Mascot = "Reds",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("6de834fc-509e-4989-b1d2-49c8b10c1ece"),
                            Location = "Cleveland",
                            Mascot = "Indians",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("da5a4c84-f866-49d3-960c-ead18a08346c"),
                            Location = "Colorado",
                            Mascot = "Rockies",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("61da07c9-a29c-4d0d-8375-7352458bd858"),
                            Location = "Detroit",
                            Mascot = "Tigers",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("093d9c05-cf42-4260-be44-ab6fb8399c38"),
                            Location = "Houston",
                            Mascot = "Astros",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("53ab3b55-5d3f-4991-bbf6-fa5874eeacf5"),
                            Location = "Kansas City",
                            Mascot = "Royals",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("2f47feaf-29fd-49b3-af5e-a5cd3ad1c68d"),
                            Location = "Los Angeles",
                            Mascot = "Angels",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("3105b032-1df3-48c7-be70-21a7ec36d4fd"),
                            Location = "Los Angeles",
                            Mascot = "Dodgers",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("b3d8a035-746e-42c0-9264-a97ec10d5e78"),
                            Location = "Miami",
                            Mascot = "Marlins",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("9aa7dd61-e5d7-4a80-8cef-e3b6e1a93920"),
                            Location = "Milwaukee",
                            Mascot = "Brewers",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("f3d27ac5-73cc-480d-bd44-11af1c8ddce9"),
                            Location = "Minnesota",
                            Mascot = "Twins",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("bde59215-f8be-415a-99e8-31ea7b96d2cf"),
                            Location = "New York",
                            Mascot = "Mets",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("09faad84-aa61-4376-93cc-6d98a3e2a941"),
                            Location = "New York",
                            Mascot = "Yankees",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("a8e4de87-8da4-4bb0-8232-642a059451fe"),
                            Location = "Oakland",
                            Mascot = "Athletics",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("a0ac8958-26bf-4d95-ae39-bba328daa3f1"),
                            Location = "Philadelphia",
                            Mascot = "Phillies",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("30f456f3-caf8-4582-829f-fdfc4ef6c520"),
                            Location = "Pittsburgh",
                            Mascot = "Pirates",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("f460874c-5ba5-4411-b602-239da45af489"),
                            Location = "San Diego",
                            Mascot = "Padres",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("60ecf028-f2b7-49bc-8649-776df8b8f225"),
                            Location = "San Francisco",
                            Mascot = "Giants",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("58e52fc4-c688-4ad2-9944-ee3e5f92337c"),
                            Location = "Seattle",
                            Mascot = "Mariners",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("10ed79cb-f213-403c-84da-c915ae5e4d4c"),
                            Location = "St. Louis",
                            Mascot = "Cardinals",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("53fa4e27-c75f-479a-aeba-94f8014446d1"),
                            Location = "Tampa Bay",
                            Mascot = "Rays",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("2f2cdf19-0cd7-4a35-881f-8cfbd8d4fea8"),
                            Location = "Texas",
                            Mascot = "Rangers",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("c03dd191-1cbd-4fe8-84b1-3dac7c839fff"),
                            Location = "Toronto",
                            Mascot = "Blue Jays",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        },
                        new
                        {
                            TeamId = new Guid("d4b12dee-abf7-41a0-b78a-d40072d5e2f8"),
                            Location = "Washington",
                            Mascot = "Nationals",
                            SportId = new Guid("a90b8447-171a-4633-b191-fa4ca83270a8")
                        });
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.GameLine", b =>
                {
                    b.HasOne("SportsbookAggregation.Data.Models.GamblingSite", "GamblingSite")
                        .WithMany()
                        .HasForeignKey("GamblingSiteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SportsbookAggregation.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.GameResult", b =>
                {
                    b.HasOne("SportsbookAggregation.Data.Models.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SportsbookAggregation.Data.Models.Team", b =>
                {
                    b.HasOne("SportsbookAggregation.Data.Models.Sport", "Sport")
                        .WithMany()
                        .HasForeignKey("SportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
